version: '3'

services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code/src
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    depends_on:
      db:
        condition: 'service_healthy'

  pg_db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: